### ISSUE TITLE
Make MaxStreams configurable

### ISSUE THREAD

**Issue by distracteddev** [segmentio/cwlogs#27]
First off, thank you for putting this project together. Its the most performant way I've found to examine CloudWatch logs.

I understand that CloudWatch does not provide a great native solution for filtering streams by name if you are not doing a prefix match. Therefore cwlogs has implemented its own in-process matching, but it caps the number of streams it searches for a particular query to 100. 

This number is too low for my purposes and was wondering if this project would consider exposing that limit as a configurable option? 

If the project is willing to do so, I'd be happy to help contribute, but I'm new to Go so would require some guidance. 

Alternatively, please consider upping the limit to 500. Searching 500 streams in my tests still allow the query to return in under 2 seconds.

**Comment by dfuentes** [comment]
Hey, thanks for the ticket.  I've just merged https://github.com/segmentio/cwlogs/pull/28 which adds a new flag `-m, --max-streams` to fetch/list to allow you to configure that value.

**Comment by distracteddev** [comment]
You are incredible! Thanks a ton 🥇
