### ISSUE TITLE
ordering of log lines

### ISSUE THREAD

**Issue by yields** [segmentio/cwlogs#31]
I noticed that cwlogs orders/sorts log lines incorrectly:

```
[ e184f96e ] 02-23 18:52:03 INFO - beginning to drop messages
[ f0bddc5b ] 02-23 18:48:53 INFO - stats/datadog: sending metrics with a buffer of size 1024 B
```

Is it expected behaviour, or does the log lines from all streams should be sorted together?

**Comment by dfuentes** [comment]
Log lines within a single stream should always be sorted.  Between different streams, cloudwatch does a "best-effort" attempt to interleave events in sorted order, but isn't always able to.  (see the `interleaved` option here https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html#API_FilterLogEvents_RequestSyntax)
